# Site settings
title: "Taskitt"
email: gerlando@gmail.com
description: "Unlimited website consulting and support for $99/mo."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.taskitt.com" # the base hostname & protocol for your site
twitter_username: gpxl
github_username:  gpxl

# Build settings
markdown: kramdown
