# Site settings
title: "Taskitt: Unlimited website support and small jobs for $99/mo."
email: gerlando@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.taskitt.com" # the base hostname & protocol for your site
twitter_username: gpxl
github_username:  gpxl

# Build settings
markdown: kramdown
